pipeline:
  build:
    image: php:${PHP}-cli
    commands:
      # Add GD extension
      # (1) Install prerequisites
      - apt update && apt install --yes curl git unzip libfreetype6-dev zlib1g-dev libpng-dev libjpeg-dev

      # (2) Install & configure GD
      - docker-php-ext-configure gd --with-jpeg --with-freetype
      - docker-php-ext-install -j$(nproc) gd

      # Install composer
      - curl -sSL https://raw.githubusercontent.com/composer/getcomposer.org/master/web/installer | php -- --install-dir=/usr/local/bin --filename=composer

      # Install dependencies
      - apt install --yes ocrad tesseract-ocr
      - composer install

      # Run PHPUnit tests
      - composer run test

    when:
      event: push

matrix:
  PHP:
    - 8.0  # EOL 2020-11-26, SS 2023-10-26
    - 8.1  # EOL 2023-11-25, SS 2024-11-25
    - 8.2  # EOL 2024-12-08, SS 2025-12-08
